### ISSUE TITLE
ReadMe Step 3: Number 11

### ISSUE THREAD

**Issue by samdevx1029** [Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore#10]
Step 3: Number 11: Instruction says:
_Find the Client ID value and copy it aside, you will need this later when configuring your application._

Nowhere do I see this "Client ID" of the service being used again in ReadMe. So what is the point of copying it and setting it aside? I suspect this is the reason this sample is failing with AccessDenied. Could you please take a look? Thanks!

**Comment by michael-freidgeim-webjet** [comment]
Have a look at corrections in Pull Request https://github.com/Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore/pull/13/commits/d8cea59d555825800af9583aa98be59d152a3ddb . It changes the reference to "Client ID". Does it clarify your question?
