### ISSUE TITLE
Issue on SelectPermissions

### ISSUE THREAD

**Issue by BlueCloudDev** [Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore#11]
When creating the applications through the new portal, everything went smoothly up until the last step. After hitting "Select an API" I was not able to find the API that I had created, despite typing in the full name of the app and searching.

I was able to get around it by deleting what I had created, making them in the old manage.windowsazure.com portal, and then returning to the new one to complete the permissions assignment. When I did this, I was able to find the applications to apply permissions.

Hope that helps!

**Comment by AkodoShado** [comment]
thank you for fix. I had the same problem.
It will be great if I could register this apps using https://apps.dev.microsoft.com

**Comment by jmprieur** [comment]
The problem you experienced in the portal does not seem to repro any longer.

This is an Azure AD V1 application, and therefore you need to register it in https://portal.azure.com. https://apps.dev.microsoft.com is for the V1 applications (signing users both in AAD and Microsoft personal account)
