### ISSUE TITLE
B2C

### ISSUE THREAD

**Issue by himadrinath** [Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore#14]
please do this same example in B2C scenario

**Comment by tanwarsatya** [comment]
Yes we need an example for B2C. Whatever samples and information is available are in only pieces with no single complete working example.

**Comment by himadrinath** [comment]
@tanwarsatya https://github.com/dzimchuk/azure-ad-b2c-asp-net-core

**Comment by gsacavdm** [comment]
Thank you for helping out @himadrinath by providing the link.
