### ISSUE TITLE
Update sample to beta 4

### ISSUE THREAD

**Issue by npnelson** [Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore#2]
Specifically (for now), I am interested in the change to 

```
app.UseOAuthBearerAuthentication(options =>
            {
                options.Audience = Configuration.Get("AzureAd:Audience");
                options.Authority = String.Format(Configuration.Get("AzureAd:AadInstance"), Configuration.Get("AzureAd:Tenant"));
            });
```

I know that it is now **UseOAuthAuthentication** and I think I have to import the **Microsoft.AspNet.Builder** namespace, but the parameters/options names have changed and I'm not sure what maps to what.

**Comment by npnelson** [comment]
Just wanted to correct myself - It is still **UseOAuthBearerAuthentication** with the same signature and options as beta3 but that got split out into a new package for beta4 **Microsoft.AspNet.Authentication.OAuthBearer**

**Comment by jmprieur** [comment]
updated to ASP.NET Core 2.0
