### ISSUE TITLE
Please update to 2.0-final as app.UseJwtBearerAuthentication is Obsolete

### ISSUE THREAD

**Issue by aredfox** [Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore#22]
app.UseJwtBearerAuthentication is obsolete and should now be configured in services
aka

```
services..AddJwtBearer() - with options if any
```

**Comment by jmprieur** [comment]
the update to ASP.NET Core 2.0 is now available (PR is https://github.com/Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore/pull/24)
