### ISSUE TITLE
How to lock down the app with Roles in Azure AD

### ISSUE THREAD

**Issue by rodneyjoyce** [Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore#27]
Hi,

I implemented the sample and it works as expected. However, one thing I noticed which seemed wierd:

My objective is to be able to lock down web apps/apis using Roles in Azure AD. If I browse to myapps.microsoft.com the app does not appear. However, if I go to the URL directly I can authenticate and add ToDo items.

I want to be able to use Roles to show or hide the app in MyApps but also control who has access to the actual web app. Is this something I need to implement at code level or can it be locked down at AppService and AD level?

Thanks

**Comment by jmprieur** [comment]
I'm not sure for AppService, but you might find useful to have a look at https://github.com/Azure-Samples/active-directory-dotnet-webapp-roleclaims
