### ISSUE TITLE
Updating Graph token

### ISSUE THREAD

**Issue by programmersommer** [Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore#29]
Hi!
It's not really an issue, it's more question.
When Graph token acquired it has a life time 1 hour. Code that could get this code is:

`private async Task OnAuthorizationCodeReceivedAsync(AuthorizationCodeReceivedContext context)
            {
                string userId = (context.Principal.FindFirst("http://schemas.microsoft.com/identity/claims/objectidentifier"))?.Value;  
                var authContext = new AuthenticationContext(context.Options.Authority, new NaiveSessionCache(userId, context.HttpContext.Session));
                var credential = new ClientCredential(context.Options.ClientId, context.Options.ClientSecret);
                var authResult = await authContext.AcquireTokenByAuthorizationCodeAsync(context.TokenEndpointRequest.Code,
                    new Uri(context.TokenEndpointRequest.RedirectUri, UriKind.RelativeOrAbsolute), credential, context.Options.Resource);
                context.HandleCodeRedemption(authResult.AccessToken, context.ProtocolMessage.IdToken);
            }`

As I see this code could be called only if logout and login again. That is not comfortable. Is there some way to change token live time or update it?
I see only way to get new token somehow with code like this:

`    AuthenticationContext authContext = new AuthenticationContext(LoginUrl + tenantId, false);
                ClientCredential credential = new ClientCredential(clientId, clientSecret);
                AuthenticationResult assertionCredential = await authContext.AcquireTokenAsync(GraphUrl, credential);
                `

**Comment by programmersommer** [comment]
was solved with AllowRefresh = true

       [HttpGet]
        public IActionResult SignOutRefreshToken()
        {
            var callbackUrl = Url.Action(nameof(SignedOut), "Account", values: null, protocol: Request.Scheme);
            return SignOut(
                new AuthenticationProperties { RedirectUri = callbackUrl, AllowRefresh = true },
                CookieAuthenticationDefaults.AuthenticationScheme,
                OpenIdConnectDefaults.AuthenticationScheme);
        }

**Comment by jmprieur** [comment]
Fixed in the sample
