### ISSUE TITLE
Please update the sample to AAD V2

### ISSUE THREAD

**Issue by KalyanChanumolu-MSFT** [Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore#35]
I see that the other [example ](https://github.com/azure-samples/active-directory-dotnet-native-aspnetcore-v2) with WPF client has been updated to AADV2 but not this one.
Could you please update the same.

Thanks

**Comment by jmprieur** [comment]
I'm actually working on it @Appjunkie

**Comment by jmprieur** [comment]
@Appjunkie 
See the following sample. The Web App is an AAD v2.0 web app, which calls an API (the Microsoft Graph)

https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/signInAndCallMsGraph (note the branch signInAndCallMsGraph signInAndCallMsGraph` as this sample is a kind of tutorial)
