### ISSUE TITLE
Failed to acquire token silently as no token was found in the cache. Call method AcquireToken

### ISSUE THREAD

**Issue by bdebaere** [Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore#36]
Using the exact code found in the sample I'm getting the following error when calling a resource on behalf of the user calling the API after an hour: "Failed to acquire token silently as no token was found in the cache. Call method AcquireToken".

It works for an hour but when it comes to refreshing the token it fails. I'm trying to access an azure analysis services cube through an API request.

How I'm getting the OBO token:
```csharp
        public static async Task<string> AcquireOnBehalfOfToken(
            string resourceId,
            string userObjectId,
            ISession session)
        {
            AuthenticationContext authContext = new AuthenticationContext(AzureAdOptions.Settings.Authority, new NaiveSessionCache(userObjectId, session));
            ClientCredential credential = new ClientCredential(AzureAdOptions.Settings.ClientId, AzureAdOptions.Settings.ClientSecret);
            var result = await authContext.AcquireTokenSilentAsync(resourceId, credential, new UserIdentifier(userObjectId, UserIdentifierType.UniqueId));
            var onBehalfOfToken = result.AccessToken;

            return onBehalfOfToken;
        }
```

My Startup.cs:
```csharp
    public class Startup
    {
        public void Configure(
            IApplicationBuilder app,
            IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            
            app.UseStaticFiles();

            app.UseSession(); // Needs to be app.UseAuthentication() and app.UseMvc() otherwise you will get an exception "Session has not been configured for this application or request."
            app.UseAuthentication();
        }

        public IConfiguration Configuration { get; }

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddAuthentication(sharedOptions =>
                {
                    sharedOptions.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                    sharedOptions.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
                })
                .AddAzureAd(options =>
                {
                    Configuration.Bind("AzureAd", options);
                    AzureAdOptions.Settings = options;
                })
                .AddCookie();
            services.AddSession();
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1).AddSessionStateTempDataProvider();
        }
    }
```

https://github.com/Azure-Samples/active-directory-dotnet-webapi-onbehalfof/issues/25

**Comment by jmprieur** [comment]
@bdebaere : is it an option for you to use client credentials? (calling cube in the name of the app, and not in the name of a user) ?

**Comment by bdebaere** [comment]
@jmprieur Unfortunately not, we need the user passed to the cube so the cube can apply authorization. Do you believe this is the cause?

**Comment by bdebaere** [comment]
@jmprieur I can share my entire project in private or have a Skype call or something if it would help.

**Comment by bdebaere** [comment]
@jmprieur I'm 99% sure that the problem was caused by the resetting of the cache during publishing and cooldown (not always on) of the API. I will switch to a persisted db cache and come back if the problem returns. Sorry for the probable waste of time.

**Comment by jmprieur** [comment]
Thanks for the update, @bdebaere. Feel free re-open if you have a consistent repo.

**Comment by Vikas-C** [comment]
Hi, I realize this thread has been closed for a while but I am facing the same error message as well when I call the `AcquireTokenSilentAsync` method. Although for me it doesn't work from the start. I've followed the sample provided and it always exits with the ADALError `failed_to_acquire_token_silently`. I've added a AdalException block to catch this and call the `AcquireTokenAsync` method when this happens. I also noticed that when the `AcquireTokenAsync` is called, the token is fetched from cache. Anything I've overlooked or missed out? Any help would be highly appreciated.

**Comment by jmprieur** [comment]
@kalyankrishna1 would you mind having a look?

**Comment by kalyankrishna1** [comment]
looking at it

**Comment by Vikas-C** [comment]
Hi @jmprieur and @kalyankrishna1 the issue got resolved. The default cookie policy being set when a new project was being created (default dotnet core web application template) was conflicting with the cookie declaration which got added with the `OpenIdConnect` definition in `Startup.cs`. Removed that and it started to work as expected. Thanks for your time.

**Comment by douglasfernandesjr** [comment]
I faced the same problem, the cookie policy mess up with the user session. To fix this i used the option **Cookie.IsEssential** in the  **AddSession** method.

```//...
    services.AddSession(opt =>
    {
        **opt.Cookie.IsEssential = true;**
    });
    //...
```

from here: [https://stackoverflow.com/questions/49317304/asp-net-core-2-1-session](https://stackoverflow.com/questions/49317304/asp-net-core-2-1-session)
