### ISSUE TITLE
User impersonation sample

### ISSUE THREAD

**Issue by bdebaere** [Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore#38]
Would it be possible to provide a sample on how to implement user impersonation which supports on behalf of authentication? I'd like to implement it in a development environment. I want downstream APIs like the Graph API or other services like Azure Analysis Services to use the impersonated user too.

**Comment by jmprieur** [comment]
@bdebaere : like this one? https://github.com/Azure-Samples/active-directory-dotnet-webapi-onbehalfof ?

**Comment by bdebaere** [comment]
@jmprieur Like the one I'm commenting on (https://github.com/Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore) but with user impersonation. I don't immediately see user impersonation in the sample you linked?

The scenario is this:
1. User calls the API with another AAD ID in the header
2. User is authenticated as a valid AAD user
3. Permissions are checked and if user can impersonate then
4. AAD ID is read from the header
5. Every call is now made as if by the user in the AAD ID header (including Graph API, Azure Analysis Services, etc.)

**Comment by jmprieur** [comment]
The code that does the OBO is there: https://github.com/Azure-Samples/active-directory-dotnet-webapi-onbehalfof/blob/master/TodoListService/Controllers/TodoListController.cs#L150-L178
