### ISSUE TITLE
This sample will not build with ASP.Net 5/MVC 6 Beta 8

### ISSUE THREAD

**Issue by steve-warwick** [Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore#4]
Could someone please update this sample to the latest beta of ASP.Net 5/MVC 6. Currently the latest release is beta 8. There appears to be significant differences between beta 3 and beta 8. For instance, Microsoft.AspNet.Security appears to be no longer supported. It looks like you need to be referencing Microsoft.AspNet.Authentication namespaces instead. The problem is these namespaces have some significant differences, so it's difficult to figure out what the necessary changes should be. It's really surprising that these samples have not been updated.

**Comment by ingAlfano** [comment]
Did anyone find any updated example?
I am very frustrated, I am looking for a working example but here and there I have outdated packages and namespaces, new Azure services, old versions of ASP.Net and so on..

**Comment by jmprieur** [comment]
No longer repros in the update for ASP.NET Core 2.0
