### ISSUE TITLE
Please update to App Registrations new experience. 

### ISSUE THREAD

**Issue by xieb0001** [Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore#43]
the App registration it deprecating the old experience, please update. it's hard to match what the doc says with what is in portal.

**Comment by joegithub** [comment]
Second this. Specifically the location for setting "Keys" and the "Application Type" have changed.

**Comment by jmprieur** [comment]
@kalyankrishna1 @TiagoBrenck if you could update the README.md ...

**Comment by TiagoBrenck** [comment]
The registration instructions got updated. 

Thanks
