### ISSUE TITLE
Upgrade to ASP.NET Core 2.1.1

### ISSUE THREAD

**Issue by markti** [Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore#46]
Please upgrade to ASP.NET Core 2.1.1

**Comment by analogrelay** [comment]
@jmprieur Can we (ASP.NET) help get these samples updated? 2.0 is out-of-support now.

**Comment by mpetrinidev** [comment]
@anurse I'd to collaborate on this

**Comment by jmprieur** [comment]
@anurse @mpetrinidev 
Actually ADAL is also no longer the recommended library.

The recommended sample (which is an ASP.NET 2.2 sample) is https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2, and in particular https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API

**Comment by mpetrinidev** [comment]
@jmprieur I'll be take a look to those samples, thank you!

**Comment by analogrelay** [comment]
Sounds good. Thanks for clarifying!

**Comment by TiagoBrenck** [comment]
Closing as we are archiving this sample. 

The newer one can be found at: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API
