### ISSUE TITLE
Small issue

### ISSUE THREAD

**Issue by MZacharias** [Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore#6]
Small issue when adding items to the todolist that wouldn't let me view the items added.  Line 56 and 57 of TodoController.cs contain references to the response element that can't be found due to the name being capitalized.  The elements need to be "title" and "owner" lowercase instead of "Title" and "Owner".

**Comment by jmprieur** [comment]
No longer repros in the update for ASP.NET Core 2.0
