### ISSUE TITLE
Recreate and publish to Azure

### ISSUE THREAD

**Issue by sgude0** [Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore#7]
Despite several attempts, I cannot publish this sample to Azure. It runs locally, but I would really  appreciate it if this sample was padded with "How to recreate" and "Publish to Azure" instructions like so many of the other samples have.

**Comment by jmprieur** [comment]
I've added information about "How the code was created" in the update for ASP.NET Core 2.0, and a paragraph on what to change to publish to Azure.
See https://github.com/Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore/pull/24/commits/3e2e837bc4769b1c74d78e3a8615f9e1336b3dd0
