### ISSUE TITLE
Deserialize fails with "No parameterless constructor defined for this object"

### ISSUE THREAD

**Issue by glatzert** [Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore#8]
I tried to get this running with ADAL 3.13, but the Deserialize throws a "no parameterless constructor defined for this object", which seems to come from the json parts of the serialized data.

The error-message itself seems odd at first, but the class AuthenticationResult does indeed not have a parameterless ctor.

**Comment by jmprieur** [comment]
Closing as this issue is a bit old, with not much context. Please reopen if this still reproes with the new updated sample to ASP.NET Core 2.0
